# .air.toml

# Directorios donde se observarán los cambios
root = "cmd/main"
tmp_dir = "tmp"

# Carpeta donde están tus archivos Go
watch_dirs = [
  "cmd",      # Carpeta donde está tu archivo main.go
  "internal", # Carpeta donde están tus manejadores, servicios y modelos
  "pkg",      # Carpeta si tienes lógica adicional en una estructura de paquetes
]

# Ignorar directorios o archivos temporales
exclude_dirs = [
  "tmp",
  "node_modules",
]

# Esto es útil si tienes una carpeta `db` o similar
# que puede no tener archivos Go pero aún así necesita ser monitoreada
watch_files = [
  "*.go",
]

# Comando para ejecutar cuando se reinicie el servidor
cmd = [
  "go", "run", ".",
]